"""initial schema

Revision ID: 6ffd7a52d3fe
Revises: 
Create Date: 2025-11-14 00:57:29.374296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ffd7a52d3fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPERATOR', 'VIEWER', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_email', 'users', ['email'], unique=False)
    op.create_index('idx_user_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'LOGIN', 'LOGOUT', 'DEPLOY', 'ROLLBACK', 'START_SERVICE', 'STOP_SERVICE', 'RESTART_SERVICE', name='auditaction'), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_data', sa.JSON(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('idx_audit_created', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_resource', 'audit_logs', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('deployment_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'SUCCESS', 'FAILED', 'ROLLED_BACK', name='deploymentstatus'), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('deployment_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('rollback_version', sa.String(length=100), nullable=True),
    sa.Column('deployment_strategy', sa.String(length=50), nullable=True),
    sa.Column('config_snapshot', sa.JSON(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_deployment_operator', 'deployment_records', ['operator_id'], unique=False)
    op.create_index('idx_deployment_status', 'deployment_records', ['status'], unique=False)
    op.create_index('idx_deployment_time', 'deployment_records', ['deployment_time'], unique=False)
    op.create_index('idx_deployment_version', 'deployment_records', ['version'], unique=False)
    op.create_index(op.f('ix_deployment_records_id'), 'deployment_records', ['id'], unique=False)
    op.create_table('service_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('config_key', sa.String(length=255), nullable=False),
    sa.Column('config_value', sa.Text(), nullable=True),
    sa.Column('config_type', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_service_config_key', 'service_configs', ['config_key'], unique=False)
    op.create_index('idx_service_config_name', 'service_configs', ['service_name'], unique=False)
    op.create_index(op.f('ix_service_configs_id'), 'service_configs', ['id'], unique=False)
    op.create_index(op.f('ix_service_configs_service_name'), 'service_configs', ['service_name'], unique=True)
    op.create_table('token_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', 'EXPIRED', name='tokenstatus'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_token_hash', 'token_records', ['token_hash'], unique=False)
    op.create_index('idx_token_status', 'token_records', ['status'], unique=False)
    op.create_index('idx_token_user', 'token_records', ['user_id'], unique=False)
    op.create_index(op.f('ix_token_records_id'), 'token_records', ['id'], unique=False)
    op.create_index(op.f('ix_token_records_token_hash'), 'token_records', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_records_token_hash'), table_name='token_records')
    op.drop_index(op.f('ix_token_records_id'), table_name='token_records')
    op.drop_index('idx_token_user', table_name='token_records')
    op.drop_index('idx_token_status', table_name='token_records')
    op.drop_index('idx_token_hash', table_name='token_records')
    op.drop_table('token_records')
    op.drop_index(op.f('ix_service_configs_service_name'), table_name='service_configs')
    op.drop_index(op.f('ix_service_configs_id'), table_name='service_configs')
    op.drop_index('idx_service_config_name', table_name='service_configs')
    op.drop_index('idx_service_config_key', table_name='service_configs')
    op.drop_table('service_configs')
    op.drop_index(op.f('ix_deployment_records_id'), table_name='deployment_records')
    op.drop_index('idx_deployment_version', table_name='deployment_records')
    op.drop_index('idx_deployment_time', table_name='deployment_records')
    op.drop_index('idx_deployment_status', table_name='deployment_records')
    op.drop_index('idx_deployment_operator', table_name='deployment_records')
    op.drop_table('deployment_records')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index('idx_audit_user', table_name='audit_logs')
    op.drop_index('idx_audit_resource', table_name='audit_logs')
    op.drop_index('idx_audit_created', table_name='audit_logs')
    op.drop_index('idx_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_user_username', table_name='users')
    op.drop_index('idx_user_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

